template_ros2_controller:
  update_rate:
    {
      type: int,
      default_value: 500,
      description: "Main control loop update rate in Hz",
    }
  joints:
    {
      type: string_array,
      default_value: [],
      description: "Joint names to control and listen to",
      read_only: true,
      validation: { unique<>: null },
    }
  rl_model_path:
    {
      type: string,
      default_value: "/home/lu/Git_Project/github/wheelbipe_rl/logs/rsl_rl/wheelbipe25_v3_flat_direct/2025-11-20_13-06-13/exported/model_gn.engine",
      description: "Path to TensorRT engine model file for reinforcement learning inference",
    }
  rl_inference_frequency:
    {
      type: int,
      default_value: 50,
      description: "Reinforcement learning inference frequency in Hz",
    }
  # sync_time_with_webots:
  #   {
  #     type: bool,
  #     default_value: true,
  #     description: "Enable time synchronization with Webots simulation time. When enabled, controller will use simulation time from Webots for timestamp alignment.",
  #   }
  